### ISSUE TITLE
gameplay - ship / ship collision handling

### ISSUE THREAD

**Issue by Bertram25** [stephenjsweeney/tbftss#12]
As a player, I would expect that ship do a small bump when colliding with one another. This could also trigger small damages, so that one can see the shield damage animation for instance when this happens.

It is a low priority feature, but adds a bit of spice to the trajectory handling.
This could also makes it interesting if you later add some asteroids/ mine fields, or big vessels interiors, ...

**Comment by stephenjsweeney** [comment]
I had this initially, but, as with friendly fire, I took it out as it resulted in frustrating gameplay. Mines will be added in a later version, but they will be proximity based.
