### ISSUE TITLE
gameplay - bar icons

### ISSUE THREAD

**Issue by Bertram25** [stephenjsweeney/tbftss#13]
(Sorry for the issue spamming, I'll stop after that one ;]) As a player, I first found confusing the bars alone + fire and missile names.

I even first thought the bottom left bar was representing the plasma cannon energy, and the bottom right the missiles.

Here are a few (CC-by 3.0) icons that could minimized and help explaining the bar meaning:
Shield: http://game-icons.net/lorc/originals/forward-field.html
Core energy: Could be the same icon than the ally one, or http://game-icons.net/lorc/originals/bubble-field.html
afterburner: http://game-icons.net/lorc/originals/afterburn.html
weapon icon: http://game-icons.net/lorc/originals/laser-blast.html or http://game-icons.net/lorc/originals/strafe.html

The missiles text could even be changed into this icon: http://game-icons.net/lorc/originals/rocket.html
Objectives icons: one of those maybe: http://game-icons.net/tags/target.html 

Cheers,

**Comment by stephenjsweeney** [comment]
Those icons didn't look good when scaled down, so I created my own in place. Should help to a certain degree, but I agree that the armour, shield, boost, and ECM meters could appear confusing. I'm hoping not to clutter the screen, as this will simply lead to information overload.

**Comment by Bertram25** [comment]
>  I'm hoping not to clutter the screen, as this will simply lead to information overload.

I completely understand that. Thanks for all the updates.
