### ISSUE TITLE
List sound and music licenses in the README.md

### ISSUE THREAD

**Issue by akien-mga** [stephenjsweeney/tbftss#15]
The credits section of the README.md is already well detailed with the names and URLs for each artist, but adding the name of the license for each track should also be done. Some of those URLs don't give precise information about the licensing, so it's difficult to establish if some files might not be un-licensed, i.e. all rights reserved and thus not suitable for distribution.

I know it's a painful work, but it's necessary to get the game packaged among other things in Linux distros.

**Comment by stephenjsweeney** [comment]
README.md has been updated (develop branch) with licenses for each sound and music file. These are mostly CC-0 and CC-BY, with a couple being CC-Sampling+.

**Comment by akien-mga** [comment]
Thanks a lot, that's very precise!

Fixed by 1475cab.
