### ISSUE TITLE
Suspect packages #2 - checkpoint out of battle area

### ISSUE THREAD

**Issue by Szunti** [stephenjsweeney/tbftss#17]
The second checkpoint was out of the map, I could see it on the radar, but couldn't get to it.

**Comment by stephenjsweeney** [comment]
Now fixed in the develop branch.

https://github.com/stephenjsweeney/tbftss/commit/5ba5fa54e75226e53760c0fb3822bf2cb998ee50

**Comment by stephenjsweeney** [comment]
This mission now works, so closing this issue.
