### ISSUE TITLE
Icons directory missing from release tarball

### ISSUE THREAD

**Issue by bentley** [stephenjsweeney/tbftss#26]
This is not exactly a github bug, but the tarball linked from [the homepage](http://www.battleforthesolarsystem.com/games/pw/#downloads) is missing the icons directory, which causes the build to fail.

    mkdir -p /usr/ports/pobj/tbftss-1.2/fake-amd64/usr/local/share/icons/hicolor/16x16/apps
    mkdir -p /usr/ports/pobj/tbftss-1.2/fake-amd64/usr/local/share/icons/hicolor/32x32/apps
    mkdir -p /usr/ports/pobj/tbftss-1.2/fake-amd64/usr/local/share/icons/hicolor/64x64/apps
    mkdir -p /usr/ports/pobj/tbftss-1.2/fake-amd64/usr/local/share/icons/hicolor/128x128/apps
    cp -p icons/tbftss-16x16.png /usr/ports/pobj/tbftss-1.2/fake-amd64/usr/local/share/icons/hicolor/16x16/apps/tbftss.png
    cp: icons/tbftss-16x16.png: No such file or directory
    gmake: *** [makefile:53: install] Error 1

**Comment by stephenjsweeney** [comment]
makefile was missing the icons directory when packaging. I've updated this in v1.21 (in the develop branch).

**Comment by stephenjsweeney** [comment]
Now fixed in v1.3.
