### ISSUE TITLE
Binary don't work for Debian Sid 32-bits & Compilation failed on "src/system/io.c:88:22: error"

### ISSUE THREAD

**Issue by goupildb** [stephenjsweeney/tbftss#29]
My OS is a Debian Sid 32-bits.
I first tried to use the binary: "tbftss-1.3-1555.linux-x86.tar.gz"
$ ./tbftss
bash: ./tbftss : impossible d'exécuter le fichier binaire : Erreur de format pour exec()
Is it a 64-bits version?

Then, i have tried to compile the source with:
$ git clone https://github.com/stephenjsweeney/tbftss /mnt/DDprc/Download/tbftss/
$ cd /mnt/DDprc/Download/tbftss/build/linux/
$ ./build.sh

The compilation failed on:
(...)
gcc  `sdl2-config --cflags` -DVERSION=1.3 -DREVISION=1557 -DDATA_DIR=\"/opt/tbftss\" -DLOCALE_DIR=\"locale\" -Wall -Wempty-body -ansi -pedantic -Werror -Wstrict-prototypes -Werror=maybe-uninitialized -Warray-bounds -g -lefence -c src/system/input.c
gcc  `sdl2-config --cflags` -DVERSION=1.3 -DREVISION=1557 -DDATA_DIR=\"/opt/tbftss\" -DLOCALE_DIR=\"locale\" -Wall -Wempty-body -ansi -pedantic -Werror -Wstrict-prototypes -Werror=maybe-uninitialized -Warray-bounds -g -lefence -c src/system/io.c
src/system/io.c: In function ‘getSaveFilePath’:
src/system/io.c:88:22: error: ‘sprintf’ may write a terminating nul past the end of the destination [-Werror=format-overflow=]
  sprintf(path, "%s/%s", app.saveDir, filename);
                      ^
src/system/io.c:88:2: note: ‘sprintf’ output 2 or more bytes (assuming 1025) into a destination of size 1024
  sprintf(path, "%s/%s", app.saveDir, filename);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
common.mk:37 : la recette pour la cible « io.o » a échouée
make: *** [io.o] Erreur 1

Same error if i launched: $ make in the main directory

**Comment by stephenjsweeney** [comment]
Are you trying this in master? If so, please try the develop branch and let me when if you're still having issues.

**Comment by goupildb** [comment]
Yes i was trying master. 

It don't work with build/linux/build.sh:
(...)
mkdir tbftss-1.3
cp -r CHANGELOG LICENSE README.md data gfx manual music sound icons src makefile* common.mk tbftss-1.3
git log --pretty=format:"%h%x09%an%x09%ad%x09%s" --date=short >tbftss-1.3/CHANGELOG.raw
fatal: ni ceci ni aucun de ses répertoires parents (jusqu'au point de montage /mnt) n'est un dépôt git
Arrêt à la limite du système de fichiers (GIT_DISCOVERY_ACROSS_FILESYSTEM n'est pas défini).
makefile:88 : la recette pour la cible « src-dist » a échouée
make: *** [src-dist] Erreur 128

But it works fine with : $ make
Thank you.

Please, could you precise on your site if the binary is a 64-bits version?

**Comment by stephenjsweeney** [comment]
The binaries were built in a 64-bit system, yes. I'll update my website to point that out.

Also, the build.sh script expects to be run from a git-enabled directory. i.e., a GitHub clone. You should stick to just running make 👍

**Comment by goupildb** [comment]
Ok. Thank you very much!
