### ISSUE TITLE
Illiad defence #4

### ISSUE THREAD

**Issue by Mark-Weston** [stephenjsweeney/tbftss#46]
The game sometimes segfaults on Illiad Defence mission number four, so I cannot complete it.
Also segfaults on exit, but that's covered by #27

OS: OpenBSD

**Comment by stephenjsweeney** [comment]
Does it happen after / during any specific, or does it seem random?

If you're able to run it through gdb, could you do so and post the backtrace?

**Comment by Mark-Weston** [comment]
It happened twice already and both times I was over 10 minutes into the mission.
Next time I will run it from gdb.

**Comment by Mark-Weston** [comment]
The version was 1.3p2

**Comment by stephenjsweeney** [comment]
Closing, as this issue is really old now and there's been on activity for many months (if this is still an issue, re-open it).
