### ISSUE TITLE
Invincible enemy bug

### ISSUE THREAD

**Issue by Mark-Weston** [stephenjsweeney/tbftss#47]
It happened twice already. At the end two different missions, I had one enemy remaining, however, you can't hit it or set target on it (with key A). Nevertheless, the enemy can fire at you or your team-mates and cause damage, and it also doesn't let you finish the game (because the kill-all-enemies objective is still not finished). The second time it happened it was on Clarke Defence 1 mission.

Version: 1.3p2

**Comment by stephenjsweeney** [comment]
This used to happen during the epic battles. It was because the AI for an already dead fighter was being reset and bringing it back to life. I believe I've found the new culprit. Please compile from master and see if it still happens.

**Comment by stephenjsweeney** [comment]
Closing, as this issue is really old now and there's been on activity for many months (if this is still an issue, re-open it).
