### ISSUE TITLE
Usability bug: map scrolling after completing mission

### ISSUE THREAD

**Issue by bentley** [stephenjsweeney/tbftss#5]
I’m playing the game on 1920×1080 resolution. After completing a mission (e.g., in Sol), the “Continue” button is in the lower left‐hand corner. Clicking it returns to the starmap screen, but since the mouse remains in that corner of the screen, the map starts scrolling instantly, which is very disorienting. It would be nice to mitigate this effect somehow.

**Comment by stephenjsweeney** [comment]
Updated in the patch branch: the mouse is now centered when returning to the galactic map. This should mitigate the scrolling.

**Comment by Bertram25** [comment]
This is also just a suggestion: Make the scrolling happen only when left clicking or like a grab gesture would be intuitive to the player.

Best regards,

**Comment by stephenjsweeney** [comment]
Fixed in develop branch.
