### ISSUE TITLE
Rothan Defense #1 is literally unbeatable

### ISSUE THREAD

**Issue by jobbautista9** [stephenjsweeney/tbftss#52]
For some reason, my ally just want to destroy things. I was about to finish the mission after disabling all those Tugs (magging is safer than using the Plasma Cannon) by destroying them one by one carefully, then my ally accidentally destroyed one of the disabled CSN fighters, failing the mission. This is very frustrating.

Version is 1.5.1, downloaded from the GitHub releases. OS is GNU/Linux.

EDIT: You gotta be kidding me, right after I destroyed all of the Tugs, my ally killed one of those fighters. This is just insane.

**Comment by jobbautista9** [comment]
Finally completed the mission. I had to remove Taylor's ATAF though from the source code. That, along with being a Tug yourself by pushing all of those disabled fighters near the jumpgate, did it for me. I was worried that I might fail the mission since I also have to protect the allied Tugs, but showing off my firepower to the Pandorans prevented them from being able to damage my Tugs.

**Comment by stephenjsweeney** [comment]
When doing this mission myself, I always used to guard the jumpgate and allow the Pandoran tugs to come to me. It's certainly a very tough one. 

I've made a tweak (commit to develop) to tell the AI to use mags only against the tugs. It means the player is then responsible for destroying the tugs themselves. Won't mean that stray fire won't kill the CSN fighters, but it reduces the odds a lot.

**Comment by jobbautista9** [comment]
Thanks @stephenjsweeney for the commit. I'm glad this game is still being maintained. Do you have a save file that is right before Rothan Defense #1? I'd like to playtest the new commit.
