### ISSUE TITLE
Ubuntu compilation issue

### ISSUE THREAD

**Issue by meissner61** [stephenjsweeney/tbftss#59]
Hello there I am trying to compile this project from source to learn from it.

I run the `make` command from the command line and it seems the only error i get is

```
/usr/local/include/SDL2/SDL_rect.h:269:41: error: ‘SDL_FLT_EPSILON’ undeclared (first use in this function); did you mean ‘FLT_EPSILON’?
  269 |     return SDL_FRectEqualsEpsilon(a, b, SDL_FLT_EPSILON);
      |                                         ^~~~~~~~~~~~~~~
      |                                         FLT_EPSILON

```

This strikes me as an error related to some kind of SDL2 mismatch version, however when I run `sdl2-config --version` I see I am on 2.25.0

Is this an outdated version for this project? When i looked in the source code it said that `This function is available since SDL 2.0.22.
`

**Comment by stephenjsweeney** [comment]
That looks like an SDL2 issue to me, rather than a fault of the game.

How have you installed SDL2? From a repository or did you download and compile the sources yourself?

**Comment by meissner61** [comment]
i compiled SDL2 from source, in fact after this error i just re-compiled it to update it to version 2.31.0 and i still get that one error but now also a lot more.
~~Could you tell me if I am correct in assuming you are using:
`sdl2`, `sdl2-image` `sdl2-ttf` any other libraries i might be missing?~~
Sorry i Just woke up I could have just checked what you're linking against

**Comment by meissner61** [comment]
Okay well i got it working i have no idea why the errors suddenly started to go away but wow...
A couple of things if anyone ever finds this issue is deffinitely just start with 
`sudo apt-get update`
`sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev`
also apparently there for the localization we need `sudo apt-get install gettext` which for me resolved a msgfmt error in the  makefile. apparently this is a tool for compiling translations.

Cheers! Im excited to dive into the code, this is one of the few not gigantic Godot style impossible to learn from projects but still big enough to comb through on my own and learn
