### ISSUE TITLE
Usability bug: switching weapons without scrollwheel

### ISSUE THREAD

**Issue by bentley** [stephenjsweeney/tbftss#6]
Please provide a way to switch weapons on mice without a scroll wheel (e.g., number keys?). Many laptops have only a three‐button mouse. Because of this I haven’t been able to complete Temper/Pirate Uprising 3.

**Comment by stephenjsweeney** [comment]
Updated in patch branch. I've gone with Z, X, and space in place of mouse wheel controls, but open to suggestions for defaults. Will bring control remapping to a later version of the game, possibly v0.6.

Z: cycle through weapons.
X: cycle radar range.
Space: launch missile.

**Comment by stephenjsweeney** [comment]
Fixed in develop branch.
